dist: bionic
sudo: false
language: go
go:
  - 1.15.x

addons:
  apt:
    packages:
      - python3 
      - python3-pip 
      - python3-setuptools

before_script:
  - scripts/detect_secrets.sh

install:
  # Required to install detect-secrets
  - sudo chmod o+rwx /usr/lib/python3/dist-packages/
  - python3 -m pip install -U pip
  - pip3 install --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"
  # This script is used by the Travis build to install a cookie for
  # go.googlesource.com so rate limits are higher when using `go get` to fetch
  # packages that live there.
  # See: https://github.com/golang/go/issues/12933
  - bash scripts/gogetcookie.sh
  - go get github.com/kardianos/govendor
  - chmod +x ./install-sonar-scanner.sh
  - source ./install-sonar-scanner.sh $SQ_URL
  - go get -u github.com/jstemmer/go-junit-report
  - go get github.com/axw/gocov/gocov
  - go get github.com/AlekSi/gocov-xml
  - if [[ $SQ_URL =~ ^https ]]; then sudo su -c "yes | keytool -import -alias mySonarServer -file sonarqubeibmcom.crt -keystore /tmp/$SQ_VERSION/jre/lib/security/cacerts -storepass changeit"; fi
  - go get github.com/rakyll/statik

script:
  - make test
  - make vet
  - chmod +x ./scannerExec.sh
  - ./scannerExec.sh

branches:
  only:
    - master
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
